version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./jellyfin/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 8096:8096
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./sonarr/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./radarr/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./bazarr/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 6767:6767
    restart: unless-stopped
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./lidarr/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 8688:8686
    restart: unless-stopped
   
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./readarr/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 8799:8787
    restart: unless-stopped
   
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    ports:
      - 8191:8191
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped


  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr/config:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
   
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - ./calibre-web/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/data
    ports:
      - 8083:8083
    restart: unless-stopped
