version: "3.6"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8085:8085 # qbittorrent
      - 6885:6881 # qbittorrent
      - 6885:6881/udp # qbittorrent
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=
      
      # Timezone for accurate log times
      - TZ=Europe/Berlin
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: gluetune/.env
    network_mode: "service:gluetun"
    environment:
      - WEBUI_PORT=8085
    volumes:
      - ./qbittorrent/config:/config
      - /media/lupos/ae56645f-0d5d-4e9b-b0e9-3a8d0464bd5c/media_data:/media_data
    restart: unless-stopped

